//
//  KnapsackItemProvider.swift
//  Knapsack
//
//  Created by Jan Posz on 14.05.2017.
//  Copyright © 2017 VORM. All rights reserved.
//

import Foundation

class KnapsackItemProvider {
    
    class func itemsWith(count: Int) -> [KnapsackItem] {
        if count > 99 {
            fatalError("Exceeding maximum.")
        }
        return Array(aLotOfItems().prefix(count))
    }

    class func items() -> [KnapsackItem] {
        return [KnapsackItem(cost: 1, weight: 51, volume: 12),
                KnapsackItem(cost: 3, weight: 62, volume: 45),
                KnapsackItem(cost: 4, weight: 75, volume: 75),
                KnapsackItem(cost: 5, weight: 87, volume: 34),
                KnapsackItem(cost: 11, weight: 44, volume: 54),
                KnapsackItem(cost: 6, weight: 57, volume: 65),
                KnapsackItem(cost: 7, weight: 64, volume: 76),
                KnapsackItem(cost: 8, weight: 79, volume: 45),
                KnapsackItem(cost: 21, weight: 85, volume: 87),
                KnapsackItem(cost: 8, weight: 66, volume: 78),
                KnapsackItem(cost: 1, weight: 45, volume: 23),
                KnapsackItem(cost: 9, weight: 78, volume: 44),
                KnapsackItem(cost: 32, weight: 83, volume: 56),
                KnapsackItem(cost: 5, weight: 35, volume: 76),
                KnapsackItem(cost: 19, weight: 9, volume: 36),
                KnapsackItem(cost: 4, weight: 81, volume: 45),
                KnapsackItem(cost: 3, weight: 77, volume: 23),
                KnapsackItem(cost: 33, weight: 64, volume: 43),
                KnapsackItem(cost: 44, weight: 49, volume: 53),
                KnapsackItem(cost: 16, weight: 53, volume: 23),
                KnapsackItem(cost: 5, weight: 65, volume: 65),
                KnapsackItem(cost: 22, weight: 77, volume: 72),
                KnapsackItem(cost: 5, weight: 53, volume: 84),
                KnapsackItem(cost: 6, weight: 46, volume: 53),
                KnapsackItem(cost: 4, weight: 5, volume: 72),
                KnapsackItem(cost: 7, weight: 39, volume: 91),
                KnapsackItem(cost: 3, weight: 71, volume: 64),
                KnapsackItem(cost: 4, weight: 44, volume: 42),
                KnapsackItem(cost: 8, weight: 52, volume: 64),
                KnapsackItem(cost: 9, weight: 31, volume: 74),
                KnapsackItem(cost: 8, weight: 67, volume: 23),
                KnapsackItem(cost: 9, weight: 73, volume: 54),
                KnapsackItem(cost: 15, weight: 83, volume: 43),
                KnapsackItem(cost: 6, weight: 35, volume: 54),
                KnapsackItem(cost: 7, weight: 58, volume: 64)];
    }

    
    class func aLotOfItems() -> [KnapsackItem] {
        return [KnapsackItem(cost: 1, weight: 51, volume: 12),
                KnapsackItem(cost: 3, weight: 62, volume: 45),
                KnapsackItem(cost: 4, weight: 75, volume: 75),
                KnapsackItem(cost: 5, weight: 87, volume: 34),
                KnapsackItem(cost: 11, weight: 44, volume: 54),
                KnapsackItem(cost: 6, weight: 57, volume: 65),
                KnapsackItem(cost: 7, weight: 64, volume: 76),
                KnapsackItem(cost: 8, weight: 79, volume: 45),
                KnapsackItem(cost: 21, weight: 85, volume: 87),
                KnapsackItem(cost: 8, weight: 66, volume: 78),
                KnapsackItem(cost: 1, weight: 45, volume: 23),
                KnapsackItem(cost: 9, weight: 78, volume: 44),
                KnapsackItem(cost: 32, weight: 83, volume: 56),
                KnapsackItem(cost: 5, weight: 35, volume: 76),
                KnapsackItem(cost: 19, weight: 9, volume: 36),
                KnapsackItem(cost: 4, weight: 81, volume: 45),
                KnapsackItem(cost: 3, weight: 77, volume: 23),
                KnapsackItem(cost: 33, weight: 64, volume: 43),
                KnapsackItem(cost: 44, weight: 49, volume: 53),
                KnapsackItem(cost: 16, weight: 53, volume: 23),
                KnapsackItem(cost: 5, weight: 65, volume: 65),
                KnapsackItem(cost: 22, weight: 77, volume: 72),
                KnapsackItem(cost: 5, weight: 53, volume: 84),
                KnapsackItem(cost: 6, weight: 46, volume: 53),
                KnapsackItem(cost: 4, weight: 5, volume: 72),
                KnapsackItem(cost: 7, weight: 39, volume: 91),
                KnapsackItem(cost: 3, weight: 71, volume: 64),
                KnapsackItem(cost: 4, weight: 44, volume: 42),
                KnapsackItem(cost: 8, weight: 52, volume: 64),
                KnapsackItem(cost: 9, weight: 31, volume: 74),
                KnapsackItem(cost: 8, weight: 67, volume: 23),
                KnapsackItem(cost: 9, weight: 73, volume: 54),
                KnapsackItem(cost: 15, weight: 83, volume: 43),
                KnapsackItem(cost: 6, weight: 35, volume: 54),
                KnapsackItem(cost: 7, weight: 58, volume: 64),
                KnapsackItem(cost: 1, weight: 51, volume: 12),
                KnapsackItem(cost: 3, weight: 62, volume: 45),
                KnapsackItem(cost: 4, weight: 75, volume: 75),
                KnapsackItem(cost: 5, weight: 87, volume: 34),
                KnapsackItem(cost: 11, weight: 44, volume: 54),
                KnapsackItem(cost: 6, weight: 57, volume: 65),
                KnapsackItem(cost: 7, weight: 64, volume: 76),
                KnapsackItem(cost: 8, weight: 79, volume: 45),
                KnapsackItem(cost: 21, weight: 85, volume: 87),
                KnapsackItem(cost: 8, weight: 66, volume: 78),
                KnapsackItem(cost: 1, weight: 45, volume: 23),
                KnapsackItem(cost: 9, weight: 78, volume: 44),
                KnapsackItem(cost: 32, weight: 83, volume: 56),
                KnapsackItem(cost: 5, weight: 35, volume: 76),
                KnapsackItem(cost: 19, weight: 9, volume: 36),
                KnapsackItem(cost: 4, weight: 81, volume: 45),
                KnapsackItem(cost: 3, weight: 77, volume: 23),
                KnapsackItem(cost: 33, weight: 64, volume: 43),
                KnapsackItem(cost: 44, weight: 49, volume: 53),
                KnapsackItem(cost: 16, weight: 53, volume: 23),
                KnapsackItem(cost: 5, weight: 65, volume: 65),
                KnapsackItem(cost: 22, weight: 77, volume: 72),
                KnapsackItem(cost: 5, weight: 53, volume: 84),
                KnapsackItem(cost: 6, weight: 46, volume: 53),
                KnapsackItem(cost: 4, weight: 5, volume: 72),
                KnapsackItem(cost: 7, weight: 39, volume: 91),
                KnapsackItem(cost: 3, weight: 71, volume: 64),
                KnapsackItem(cost: 4, weight: 44, volume: 42),
                KnapsackItem(cost: 8, weight: 52, volume: 64),
                KnapsackItem(cost: 9, weight: 31, volume: 74),
                KnapsackItem(cost: 8, weight: 67, volume: 23),
                KnapsackItem(cost: 9, weight: 73, volume: 54),
                KnapsackItem(cost: 15, weight: 83, volume: 43),
                KnapsackItem(cost: 6, weight: 35, volume: 54),
                KnapsackItem(cost: 7, weight: 58, volume: 64),
                KnapsackItem(cost: 1, weight: 51, volume: 12),
                KnapsackItem(cost: 3, weight: 62, volume: 45),
                KnapsackItem(cost: 4, weight: 75, volume: 75),
                KnapsackItem(cost: 5, weight: 87, volume: 34),
                KnapsackItem(cost: 11, weight: 44, volume: 54),
                KnapsackItem(cost: 6, weight: 57, volume: 65),
                KnapsackItem(cost: 7, weight: 64, volume: 76),
                KnapsackItem(cost: 8, weight: 79, volume: 45),
                KnapsackItem(cost: 21, weight: 85, volume: 87),
                KnapsackItem(cost: 8, weight: 66, volume: 78),
                KnapsackItem(cost: 1, weight: 45, volume: 23),
                KnapsackItem(cost: 9, weight: 78, volume: 44),
                KnapsackItem(cost: 32, weight: 83, volume: 56),
                KnapsackItem(cost: 5, weight: 35, volume: 76),
                KnapsackItem(cost: 19, weight: 9, volume: 36),
                KnapsackItem(cost: 4, weight: 81, volume: 45),
                KnapsackItem(cost: 3, weight: 77, volume: 23),
                KnapsackItem(cost: 33, weight: 64, volume: 43),
                KnapsackItem(cost: 44, weight: 49, volume: 53),
                KnapsackItem(cost: 16, weight: 53, volume: 23),
                KnapsackItem(cost: 5, weight: 65, volume: 65),
                KnapsackItem(cost: 22, weight: 77, volume: 72),
                KnapsackItem(cost: 5, weight: 53, volume: 84),
                KnapsackItem(cost: 6, weight: 46, volume: 53),
                KnapsackItem(cost: 4, weight: 5, volume: 72),
                KnapsackItem(cost: 7, weight: 39, volume: 91),
                KnapsackItem(cost: 3, weight: 71, volume: 64),
                KnapsackItem(cost: 4, weight: 44, volume: 42),
                KnapsackItem(cost: 8, weight: 52, volume: 64),
                KnapsackItem(cost: 9, weight: 31, volume: 74),
                KnapsackItem(cost: 8, weight: 67, volume: 23),
                KnapsackItem(cost: 9, weight: 73, volume: 54),
                KnapsackItem(cost: 15, weight: 83, volume: 43),
                KnapsackItem(cost: 6, weight: 35, volume: 54),
                KnapsackItem(cost: 7, weight: 58, volume: 64)];
    }
}
